In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data_URL = '/content/drive/MyDrive/BigDataIproject/datasets/'

In [ ]:
import pandas as pd
import numpy as np
import unicodedata
pd.set_option('display.max_columns', None)

In [ ]:
season = 1996

In [ ]:
df = pd.read_csv(f"{data_URL}nbastats/nbastats_{season}.csv")

In [ ]:
df.head()

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,29600001,1,12,0,1,11:15 PM,12:00,NaN,Start of 1st Period (11:15 PM EST),NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0
1,29600001,2,10,0,1,11:16 PM,12:00,Jump Ball Ellison vs. Longley: Tip to Harper,NaN,NaN,NaN,NaN,4,442,Pervis Ellison,1.610613e+09,Boston,Celtics,BOS,5,26,Luc Longley,1.610613e+09,Chicago,Bulls,CHI,5,166,Ron Harper,1.610613e+09,Chicago,Bulls,CHI,0
2,29600001,4,1,5,1,11:16 PM,11:39,NaN,NaN,Rodman Layup (2 PTS) (Longley 1 AST),2 - 0,-2,5,23,Dennis Rodman,1.610613e+09,Chicago,Bulls,CHI,5,26,Luc Longley,1.610613e+09,Chicago,Bulls,CHI,4,0,NaN,1.610613e+09,Boston,Celtics,BOS,0
3,29600001,5,6,2,1,11:16 PM,11:39,Ellison S.FOUL (P1.T1),NaN,NaN,NaN,NaN,4,442,Pervis Ellison,1.610613e+09,Boston,Celtics,BOS,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0
4,29600001,6,3,10,1,11:17 PM,11:39,NaN,NaN,Rodman Free Throw 1 of 1 (3 PTS),3 - 0,-3,5,23,Dennis Rodman,1.610613e+09,Chicago,Bulls,CHI,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0

# Process NBAstats

In [ ]:
def load_nbastats(season):
    nbastats = pd.read_csv(f"{data_URL}nbastats/nbastats_{season}.csv",
                          converters={'PLAYER1_TEAM_ID': str, 'PLAYER2_TEAM_ID': str,'PLAYER3_TEAM_ID': str,
                                     'PLAYER1_ID': str, 'PLAYER2_ID': str, 'PLAYER3_ID': str})

    nbastats = nbastats[nbastats['EVENTMSGTYPE'] <= 5]
    nbastats = nbastats[nbastats['EVENTMSGTYPE'] != 4]

    nbastats['HOMEDESCRIPTION'] = nbastats['HOMEDESCRIPTION'].fillna('')
    nbastats['NEUTRALDESCRIPTION'] = nbastats['NEUTRALDESCRIPTION'].fillna('')
    nbastats['VISITORDESCRIPTION'] = nbastats['VISITORDESCRIPTION'].fillna('')
    nbastats['DESCRIPTION'] = nbastats['HOMEDESCRIPTION'].astype(str) + nbastats['NEUTRALDESCRIPTION'].astype(str) + nbastats['VISITORDESCRIPTION'].astype(str)

    nbastats.loc[nbastats['DESCRIPTION'].str.contains(' BLK\)'), 'PERSON2TYPE'] = nbastats['PERSON3TYPE']
    nbastats.loc[nbastats['DESCRIPTION'].str.contains(' BLK\)'), 'PLAYER2_ID'] = nbastats['PLAYER3_ID']
    nbastats.loc[nbastats['DESCRIPTION'].str.contains(' BLK\)'), 'PLAYER2_NAME'] = nbastats['PLAYER3_NAME']
    nbastats.loc[nbastats['DESCRIPTION'].str.contains(' BLK\)'), 'PLAYER2_TEAM_ID'] = nbastats['PLAYER3_TEAM_ID']

    nbastats = nbastats[['GAME_ID', 'EVENTNUM', 'EVENTMSGTYPE', 'PERIOD', 'PCTIMESTRING', 'DESCRIPTION', 'SCOREMARGIN',
                         'PLAYER1_ID', 'PLAYER1_NAME', 'PLAYER1_TEAM_ID', 'PLAYER1_TEAM_CITY', 'PLAYER1_TEAM_NICKNAME',
                         'PLAYER1_TEAM_ABBREVIATION', 'PLAYER2_ID', 'PLAYER2_NAME']]

    nbastats[['MINUTES', 'SECONDS']] = nbastats['PCTIMESTRING'].str.split(':', expand=True)
    nbastats[['MINUTES', 'SECONDS']] = nbastats[['MINUTES', 'SECONDS']].astype({'MINUTES': 'int', 'SECONDS': 'int'})


    nbastats['PLAYER1_TEAM_ID'] = nbastats['PLAYER1_TEAM_ID'].fillna('')
    nbastats['PLAYER2_ID'] = nbastats['PLAYER2_ID'].str.replace(r'^0$', '', regex=True)
    nbastats = nbastats[nbastats['PLAYER1_TEAM_ID'] != '']

    nbastats['SEASON'] = season

    return nbastats

<>:14: SyntaxWarning: invalid escape sequence '\)'
<>:15: SyntaxWarning: invalid escape sequence '\)'
<>:16: SyntaxWarning: invalid escape sequence '\)'
<>:17: SyntaxWarning: invalid escape sequence '\)'
<>:14: SyntaxWarning: invalid escape sequence '\)'
<>:15: SyntaxWarning: invalid escape sequence '\)'
<>:16: SyntaxWarning: invalid escape sequence '\)'
<>:17: SyntaxWarning: invalid escape sequence '\)'
/tmp/ipython-input-2240567083.py:14: SyntaxWarning: invalid escape sequence '\)'
  nbastats.loc[nbastats['DESCRIPTION'].str.contains(' BLK\)'), 'PERSON2TYPE'] = nbastats['PERSON3TYPE']
/tmp/ipython-input-2240567083.py:15: SyntaxWarning: invalid escape sequence '\)'
  nbastats.loc[nbastats['DESCRIPTION'].str.contains(' BLK\)'), 'PLAYER2_ID'] = nbastats['PLAYER3_ID']
/tmp/ipython-input-2240567083.py:16: SyntaxWarning: invalid escape sequence '\)'
  nbastats.loc[nbastats['DESCRIPTION'].str.contains(' BLK\)'), 'PLAYER2_NAME'] = nbastats['PLAYER3_NAME']
/tmp/ipython-input-2240567083.py:17: SyntaxWarning: invalid escape sequence '\)'
  nbastats.loc[nbastats['DESCRIPTION'].str.contains(' BLK\)'), 'PLAYER2_TEAM_ID'] = nbastats['PLAYER3_TEAM_ID']

# Process Shotdetail

In [ ]:
df = pd.read_csv(f"{data_URL}shotdetail/shotdetail_{season}.csv")

In [ ]:
df.head()

,GRID_TYPE,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,EVENT_TYPE,ACTION_TYPE,SHOT_TYPE,SHOT_ZONE_BASIC,SHOT_ZONE_AREA,SHOT_ZONE_RANGE,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_ATTEMPTED_FLAG,SHOT_MADE_FLAG,GAME_DATE,HTM,VTM
0,Shot Chart Detail,29600005,7,120,Steven Smith,1610612737,Atlanta Hawks,1,11,8,Made Shot,Driving Layup Shot,2PT Field Goal,Restricted Area,Center(C),Less Than 8 ft.,0,0,0,1,1,19961101,MIA,ATL
1,Shot Chart Detail,29600005,9,120,Steven Smith,1610612737,Atlanta Hawks,1,10,32,Missed Shot,Jump Shot,2PT Field Goal,Mid-Range,Right Side(R),16-24 ft.,16,153,71,1,0,19961101,MIA,ATL
2,Shot Chart Detail,29600005,17,363,Christian Laettner,1610612737,Atlanta Hawks,1,9,38,Made Shot,Jump Shot,2PT Field Goal,Mid-Range,Left Side(L),8-16 ft.,10,-103,26,1,1,19961101,MIA,ATL
3,Shot Chart Detail,29600005,20,120,Steven Smith,1610612737,Atlanta Hawks,1,8,57,Missed Shot,Layup Shot,2PT Field Goal,Restricted Area,Center(C),Less Than 8 ft.,0,0,0,1,0,19961101,MIA,ATL
4,Shot Chart Detail,29600005,21,87,Dikembe Mutombo,1610612737,Atlanta Hawks,1,8,56,Missed Shot,Tip Shot,2PT Field Goal,Restricted Area,Center(C),Less Than 8 ft.,0,0,0,1,0,19961101,MIA,ATL

In [ ]:
def load_shotdetail(season):
    shotdetail = pd.read_csv(f"{data_URL}shotdetail/shotdetail_{season}.csv")

    shotdetail['ACTION_TYPE'] = shotdetail['ACTION_TYPE'].str.upper()

    shotdetail['ACTION_TYPE'] = np.where(shotdetail['ACTION_TYPE'].str.contains('TURNAROUND BANK'),
                                             shotdetail['ACTION_TYPE'].str.replace('BANK', 'JUMP BANK'), shotdetail['ACTION_TYPE'])

    shotdetail['ACTION_TYPE'] = np.where(shotdetail['ACTION_TYPE'].str.contains('FADEAWAY SHOT'),
                                             shotdetail['ACTION_TYPE'].str.replace('FADEAWAY', 'JUMP FADEAWAY'), shotdetail['ACTION_TYPE'])

    # Get Any Text before Shot Method appears in String
    regex_pattern = r"^(.*?)(\b\w+ SHOT)$"
    shotdetail[['SHOT_ATTRIBUTES', 'SHOT_METHOD']] = shotdetail['ACTION_TYPE'].astype(str).str.extract(regex_pattern)

    shotdetail = shotdetail[['GAME_ID', 'GAME_EVENT_ID', 'ACTION_TYPE', 'SHOT_TYPE', 'SHOT_ZONE_BASIC', 'SHOT_ZONE_AREA', 'SHOT_ZONE_RANGE',
                               'SHOT_DISTANCE', 'LOC_X', 'LOC_Y', 'SHOT_ATTEMPTED_FLAG', 'SHOT_MADE_FLAG', 'SHOT_ATTRIBUTES', 'SHOT_METHOD', 'GAME_DATE', 'HTM', 'VTM']]

    #shotdetail['SHOT_ATTRIBUTES'] = shotdetail['SHOT_ATTRIBUTES'].str.strip()
    shotdetail['SHOT_ATTRIBUTES'] = shotdetail['SHOT_ATTRIBUTES'].str.replace("-", "")
    shotdetail["SHOT_ZONE_BASIC"] = shotdetail['SHOT_ZONE_BASIC'].str.replace("Left ", "").str.replace("Right ", "")
    shotdetail["SHOT_ZONE_AREA"]= shotdetail['SHOT_ZONE_AREA'].str.replace("Left Side Center(LC)", "Left Side")
    shotdetail["SHOT_ZONE_AREA"]= shotdetail['SHOT_ZONE_AREA'].str.replace("Right Side Center(RC)", "Right Side")
    shotdetail["SHOT_ZONE_AREA"]= shotdetail['SHOT_ZONE_AREA'].str.replace(r'\(.*?\)', '', regex=True)

    shotdetail['SHOT_ATTEMPTED_FLAG'] = shotdetail['SHOT_ATTEMPTED_FLAG'].astype(bool)
    shotdetail['SHOT_MADE_FLAG'] = shotdetail['SHOT_MADE_FLAG'].astype(bool)

    attr_cols = ["ALLEY OOP", "BANK", "CUTTING", "DRIVING", "FLOATING", "PULLUP", "PUTBACK", "RUNNING", "REVERSE", "STEP BACK", "TIP"]
    for attr in attr_cols:
        shotdetail[attr] = np.where(shotdetail['SHOT_ATTRIBUTES'].str.contains(attr), True, False)

    shotdetail = shotdetail.drop('SHOT_ATTRIBUTES', axis=1)

    return shotdetail

# Join Files Together for Both Datasets

In [ ]:
nbastats2024 = load_nbastats(2024)
nbastats2023 = load_nbastats(2023)
nbastats2022 = load_nbastats(2022)
nbastats = pd.concat([nbastats2024, nbastats2023, nbastats2022])

shotdetail2024 = load_shotdetail(2024)
shotdetail2023 = load_shotdetail(2023)
shotdetail2022 = load_shotdetail(2022)
shotdetail = pd.concat([shotdetail2024, shotdetail2023, shotdetail2022])

# Making Additional Data Files

> Add blockquote

## Make Players File

In [ ]:
nba_players1 = nbastats.drop_duplicates(subset=['PLAYER1_ID', 'PLAYER1_NAME'])
nba_players2 = nbastats.drop_duplicates(subset=['PLAYER2_ID', 'PLAYER2_NAME'])

nba_players1 = nba_players1[['PLAYER1_ID', 'PLAYER1_NAME']]
nba_players2 = nba_players2[['PLAYER2_ID', 'PLAYER2_NAME']]
nba_players2 = nba_players2[nba_players2['PLAYER2_ID'] != 0]

nba_players1 = nba_players1.rename(columns={'PLAYER1_ID': 'ID', 'PLAYER1_NAME': 'Name'})
nba_players2 = nba_players2.rename(columns={'PLAYER2_ID': 'ID', 'PLAYER2_NAME': 'Name'})

nba_players = pd.concat([nba_players1, nba_players2], ignore_index=True)
nba_players['Name'] = nba_players['Name'].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')

nba_players = nba_players.drop_duplicates(subset=['ID'])

nba_players.to_csv(f"{data_URL}sample/players.csv", index=False)

In [ ]:
teams = nbastats[['PLAYER1_TEAM_ID', 'PLAYER1_TEAM_CITY', 'PLAYER1_TEAM_NICKNAME', 'PLAYER1_TEAM_ABBREVIATION']]
teams = teams.rename(columns={'PLAYER1_TEAM_ID': 'ID', 'PLAYER1_TEAM_CITY': 'City',
                              'PLAYER1_TEAM_NICKNAME': 'Nickname', 'PLAYER1_TEAM_ABBREVIATION' : 'Abbreviation'})
teams = teams[teams['ID'] != '']
teams = teams.drop_duplicates()

teams.to_csv(f"{data_URL}sample/teams.csv", index=False)

## Matchups

In [ ]:
games = shotdetail[['GAME_ID', 'GAME_DATE', 'HTM', 'VTM']]
games = games[games['GAME_DATE'] != '']
games = games.drop_duplicates()

games['GAME_DATE'] = pd.to_datetime(games['GAME_DATE'], format='%Y%m%d')

games = pd.merge(games, teams, left_on=['HTM'], right_on=['Abbreviation'], how='inner')
games = games.rename(columns={'ID': 'HOME_ID'})

games = pd.merge(games, teams, left_on=['VTM'], right_on=['Abbreviation'], how='inner')
games = games.rename(columns={'ID': 'AWAY_ID'})
games = games[['GAME_ID', 'GAME_DATE', 'HOME_ID', 'AWAY_ID']]

games.to_csv(f"{data_URL}sample/games.csv", index=False)

# Melting and Finalizing DF

In [ ]:
# Get Opponenet
#games = pd.read_csv("C:/Users/chann/Documents/CMPT732_BD/Project/datasets/sample/games.csv")
nbastats = pd.merge(nbastats, games, on='GAME_ID', how='inner')
nbastats['OPPONENT'] = np.where(nbastats['PLAYER1_TEAM_ID'] == nbastats['HOME_ID'], nbastats['AWAY_ID'], nbastats['HOME_ID'])

In [ ]:
# Drop Uneeded Columns now
nbastats = nbastats.drop(['PLAYER1_NAME', 'PLAYER2_NAME', 'PLAYER1_TEAM_CITY', 'PLAYER1_TEAM_NICKNAME', 'PLAYER1_TEAM_ABBREVIATION', 'HOME_ID', 'AWAY_ID'], axis=1)
shotdetail =  shotdetail.drop(['HTM', 'VTM', 'GAME_DATE'], axis=1)

In [ ]:
# Joining with Shotdetail and Create Column for Melt
nbadata = pd.merge(nbastats, shotdetail, left_on=['GAME_ID', 'EVENTNUM'], right_on=['GAME_ID', 'GAME_EVENT_ID'], how='left')

nbadata = nbadata.drop('GAME_EVENT_ID', axis=1)

In [ ]:
# Melting (Not Needed)
#nbadata["GAME_EVENT_ID"] = nbadata["GAME_ID"].astype(str) + "_" + nbadata["EVENTNUM"].astype(str)

#melted = pd.melt(nbadata, id_vars=['GAME_EVENT_ID'], value_vars=['PLAYER1_ID', 'PLAYER2_ID'])
#melted = melted[melted['value'] != '']
#melted = melted.rename(columns={'variable': 'PLAYER_ROLE', 'value': 'PLAYER_ID'})
#nbadata = pd.merge(nbadata, melted, on=['GAME_EVENT_ID'], how='inner')
#melted

In [ ]:
# Writing to Files

# Write Files to Parquet

In [ ]:
nbadata.to_parquet(
    f"{data_URL}sample/player_data",
    engine='pyarrow',
    partition_cols=['PLAYER1_ID'],
    index=False
)

nbadata[nbadata['PLAYER2_ID'] != ''].to_parquet(
    f"{data_URL}sample/player_data",
    engine='pyarrow',
    partition_cols=['PLAYER2_ID'],
    index=False
)

nbadata.to_parquet(
    f"{data_URL}sample/season_data",
    engine='pyarrow',
    partition_cols=['SEASON'],
    index=False
)

# Generate Totals for Each Season (Percentile Plots)

In [ ]:
totals = nbadata.copy()
totals = totals[totals['EVENTMSGTYPE'] <= 5]
totals['POINTS'] = np.where((totals['EVENTMSGTYPE'] == 3) & (~totals['DESCRIPTION'].str.contains(r'^MISS')), 1, 0)
totals['POINTS'] = np.where((totals['SHOT_TYPE'] == '3PT Field Goal') & (totals['SHOT_MADE_FLAG'] == 1), 3, totals['POINTS'])
totals['POINTS'] = np.where((totals['SHOT_TYPE'] == '2PT Field Goal') & (totals['SHOT_MADE_FLAG'] == 1), 2, totals['POINTS'])

points = totals.groupby(['SEASON', 'PLAYER1_ID'])['POINTS'].sum()
FTA = totals[totals['EVENTMSGTYPE'] == 3].groupby(['SEASON', 'PLAYER1_ID'])['EVENTMSGTYPE'].count()
FGA = totals[totals['EVENTMSGTYPE'] < 3].groupby(['SEASON', 'PLAYER1_ID'])['SHOT_DISTANCE'].agg(['mean', 'count'])
AST = totals[(totals['EVENTMSGTYPE'] < 3) & (totals['SHOT_MADE_FLAG'] == 1) & (totals['PLAYER2_ID'] != 0)].groupby(['SEASON', 'PLAYER2_ID'])['EVENTMSGTYPE'].count()
TOV = totals[totals['EVENTMSGTYPE'] == 5].groupby(['SEASON', 'PLAYER1_ID'])['EVENTMSGTYPE'].count()

points = points.reset_index().rename(columns={'PLAYER1_ID': 'ID'})
FTA = FTA.reset_index().rename(columns={'PLAYER1_ID': 'ID', 'EVENTMSGTYPE': 'FTA'})
FGA = FGA.reset_index().rename(columns={'PLAYER1_ID': 'ID', 'mean': 'SHOT_DISTANCE', 'count' : 'FGA'})
AST = AST.reset_index().rename(columns={'PLAYER2_ID': 'ID', 'EVENTMSGTYPE': 'AST'})
TOV = TOV.reset_index().rename(columns={'PLAYER1_ID': 'ID', 'EVENTMSGTYPE': 'TOV'})

totals = pd.merge(points, FTA, on=['SEASON', 'ID'], how='outer')
totals = pd.merge(totals, FGA, on=['SEASON', 'ID'], how='outer')
totals = pd.merge(totals, AST, on=['SEASON', 'ID'], how='outer')
totals = pd.merge(totals, TOV, on=['SEASON', 'ID'], how='outer')

totals = totals.fillna(0)
totals['PPP'] = totals['POINTS']/(totals['FGA']+0.44*totals['FTA']+totals['TOV'])
totals['TS%'] = totals['POINTS']/(2*(totals['FGA']+0.44*totals['FTA']))*100
totals['AST/TOV'] = totals['AST']/totals['TOV']
totals['FTr'] = totals['FTA']/totals['FGA']
totals

,SEASON,ID,POINTS,FTA,SHOT_DISTANCE,FGA,AST,TOV,PPP,TS%,AST/TOV,FTr
0,2022,,0.0,0.0,0.000000,0.0,40981.0,0.0,NaN,NaN,inf,NaN
1,2022,101108,819.0,160.0,17.494012,668.0,524.0,114.0,0.960817,55.457746,4.596491,0.239521
2,2022,1626145,823.0,100.0,16.138028,710.0,417.0,74.0,0.993961,54.575597,5.635135,0.140845
3,2022,1626149,320.0,101.0,3.540670,209.0,33.0,35.0,1.109416,63.131313,0.942857,0.483254
4,2022,1626153,369.0,60.0,13.849315,292.0,194.0,44.0,1.018212,57.945980,4.409091,0.205479
...,...,...,...,...,...,...,...,...,...,...,...,...
1674,2024,203999,2071.0,451.0,11.051320,1364.0,716.0,230.0,1.155408,66.274545,3.113043,0.330645
1675,2024,204001,818.0,199.0,15.505226,574.0,87.0,53.0,1.144760,61.823569,1.641509,0.346690
1676,2024,204060,15.0,0.0,18.869565,23.0,23.0,9.0,0.468750,32.608696,2.555556,0.000000
1677,2024,204456,720.0,77.0,8.626603,624.0,351.0,109.0,0.938869,54.721226,3.220183,0.123397
1678,2024,2544,1710.0,331.0,12.949606,1270.0,575.0,260.0,1.020506,60.396711,2.211538,0.260630

In [ ]:
totals.to_parquet(
    f"{data_URL}sample/season_totals",
    engine='pyarrow',
    partition_cols=['SEASON'],
    index=False
)

# PERCENTILING (Can Ignore for Dataset in Spakr just testing for plots)

In [ ]:
from scipy import stats
totals_22 = totals[totals['SEASON'] == 2022]

PPP = 0.960817

percentile_rank_scipy = stats.percentileofscore(totals_22['PPP'], 1.05, kind='rank')
percentile_rank_scipy

np.float64(nan)

In [ ]:
# https://seaborn.pydata.org/examples/pairgrid_dotplot.html shot method / attribute / value is FG%

# Column for each shot type/method 1/0s
# Get count of attempts + type % of shots they take that are that type